services:
  # -- Frontend Service for Development Environment --
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents overwriting node_modules on the container
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL}
      CHOKIDAR_USEPOLLING: "true" # Enables file watching in Docker on some systems

  # -- Backend Service for Development Environment --
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/GraphQL/Dockerfile
    ports:
      - "5000:8080"
    environment:
      MySqlConnectionString: ${MySqlConnectionString}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      Auth0Audience: ${Auth0Audience}
      Auth0Domain: ${Auth0Domain}
      IssuerSigningKey: ${IssuerSigningKey}
  seed_data:
    container_name: seeddata
    build:
      context: .
      dockerfile: SeedData/SeedData/Dockerfile
    depends_on:
      - mysql
      - mongodb1
      - mongodb2
      - mongodb3
      - neo4j
    environment:
      SEED_SAMPLE_DATA: true
      MySqlConnectionString: ${MySqlConnectionString}
      MongoDbConnectionString: ${MongoDbConnectionString}
      MongoDbDatabase: ${MongoDbDatabase}
      DATA_ROOT: /mySql

      NEO4J_URI: ${NEO4J_URI}
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    volumes:
      - ./SeedData/SeedData/mySql:/mySql

  #-- MySQL Service for Development Environment --
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: imdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  #-- MongoDB Service for Development Environment --
  mongodb1:
    image: mongo:8.0
    container_name: mongodb1
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb1:27017',priority:1},{_id:1,host:'mongodb2:27017',priority:0.5},{_id:2,host:'mongodb3:27017',priority:0.5}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongodb1_data:/data/db"
      - "mongodb1_config:/data/configdb"

  mongodb2:
    image: mongo:8.0
    container_name: mongodb2
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27018:27017
    volumes:
      - "mongodb2_data:/data/db"
      - "mongodb2_config:/data/configdb"

  mongodb3:
    image: mongo:8.0
    container_name: mongodb3
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27019:27017
    volumes:
      - "mongodb3_data:/data/db"
      - "mongodb3_config:/data/configdb"

  #-- Neo4j Service for Development Environment --
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/admin123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

volumes:
  mysql-data:
  neo4j-data:
  seeddata-data:
  mongodb1_data:
  mongodb2_data:
  mongodb3_data:
  mongodb1_config:
  mongodb2_config:
  mongodb3_config:
