services:
  #-- Frontend Service for Development Environment --
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile.dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules # Prevents overwriting node_modules on the container
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     VITE_API_URL: http://localhost:5000

  seed_data:
    container_name: seeddata
    build:
      context: .
      dockerfile: SeedData/Dockerfile
    depends_on:
      - mysql
      - mongodb
      - neo4j
    environment:
      SEED_SAMPLE_DATA: true
      ConnectionStringDocker: server=mysql;port=3306;database=imdb;user=root;password=admin;default command timeout=600
      MongoDbConnectionStr: mongodb://mongodb:27017
      MongoDbDatabase: imdb
      DATA_ROOT: /mySql
    volumes:
      - ./SeedData/SeedData/mySql:/mySql

  #-- MySQL Service for Development Environment --
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: imdb
      # MYSQL_NET_WRITE_TIMEOUT: 600
      # MYSQL_NET_READ_TIMEOUT: 600
      # MYSQL_WAIT_TIMEOUT: 600
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  #-- MongoDB Service for Development Environment --
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

  #-- Neo4j Service for Development Environment --
  neo4j:
    image: neo4j:5.26
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/admin123
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - neo4j-data:/data

volumes:
  mysql-data:
  mongodb-data:
  neo4j-data:
  seeddata-data:
