name: CI Docker Build and Push <NAME OF YOUR DOCKER IMAGE>

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        # uses: docker/login-action@v3
        uses: ./
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This section is used to lowercase the repo owner and prepare variables for image name and tag
      - name: Prepare image variables
        run: |
          # Lowercase the repo owner and export variables for all steps
          OWNER="${{ github.repository_owner }}"
          # Owner name in lowercase
          OWNER="${OWNER,,}"

          # Repository name in lowercase
          REPOSITORY="${{ github.repository }}"
          REPOSITORY="${REPOSITORY,,}"

          IMAGE_NAME="ghcr.io/$OWNER/$REPOSITORY"
          # Use the commit SHA as the image tag and identify the image uniquely
          TAG=${{ github.sha }} 

          # Export variables to environment for later steps
          echo "OWNER=$OWNER" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest ./<PATH_TO_YOUR_DOCKERFILE_DIRECTORY>

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
