name: Deply Frontend Workflow

on:
  workflow_call:
    secrets:
      BREZOR_DEPLOY_HOOK:
        required: true

jobs:
  deploy-frontend:
    name: Deploy Frontend Application
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        # if: github.ref == 'refs/heads/main'
        run: |
          curl "$BREZOR_DEPLOY_HOOK"
