name: Deply Frontend Workflow

on:
  workflow_call:
    secrets:
      BREZOR_DEPLOY_HOOK:
        required: true

jobs:
  deploy-frontend:
    name: Deploy Frontend Application
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Filter Frontend Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Deploy Frontend if Changes Detected
        if: steps.changes.outputs.frontend == 'true'
        env:
          BREZOR_DEPLOY_HOOK: ${{ secrets.BREZOR_DEPLOY_HOOK }}
        run: |
          curl "$BREZOR_DEPLOY_HOOK"
