name: Deploy Frontend Workflow

on:
  workflow_call:
    secrets:
      BREZOR_DEPLOY_HOOK:
        required: true
      REX_RENDER_DEPLOY_HOOK:
        required: true

jobs:
  deploy-frontend:
    name: Deploy Frontend Application
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - name: Deploy Frontend via Deploy Hook
        if: github.ref == 'refs/heads/main'
        env:
          BREZOR_DEPLOY_HOOK: ${{ secrets.BREZOR_DEPLOY_HOOK }}
          REX_RENDER_DEPLOY_HOOK: ${{ secrets.REX_RENDER_DEPLOY_HOOK }}
        run: |
          curl "$BREZOR_DEPLOY_HOOK"
          curl "$REX_RENDER_DEPLOY_HOOK"