# name: Deploy

# on: 
#   push:
#     branches: [ main ]

# jobs:
#   backend-build-and-tests:
#     runs-on: ubunto-latest
#     steps:
#       - uses: actions/checkout@v5
#       - uses: actions/setup-dotnet@v4
#         with: 
#           dotnet-version: "9.0.x"
#       - name: Build backend
#         run: dotnet build backend

#   frontend-build-and-tests:
#     runs-on: ubunto-latest
#     steps:
#       - uses: actions/checkout@v5
#       - uses: actions/setup-node@v4
#         with: 
#           node-version: 20
#       - name: Build frontend
#         working-directory: frontend # <- RET sti
#         run: |
#           npm ci
#           npm run build
  
#   integration-tests:
#     needs: [ backend-build-and-tests ]
#     uses: ./.github/workflows/integration-tests.yml
#     secrets: inherit

#   e2e-tests:
#     needs:
#       - frontend-build-and-tests
#       - backend-build-and-tests
#       - integration-tests
#     uses: ./.github/workflows/e2e-tests.yml
#     secrets: inherit

#   deploy:
#     needs: e2e-tests
#     runs-on: ubunto-latest
#     steps:
#       - name: Deploy...
#         run: echo "Her kÃ¸rer deploy (docker)"
